# Generated by Django 2.1.3 on 2018-11-09 19:07

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='0001/ghg', max_length=10, verbose_name='Número')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Arquivado', 'Arquivado'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=10, verbose_name='Status')),
                ('assunto', models.CharField(max_length=30, verbose_name='Assunto')),
                ('referencia', models.CharField(max_length=30, verbose_name='Referência')),
                ('anexo', models.CharField(max_length=30, verbose_name='Anexo')),
                ('data', models.DateField(verbose_name='Data')),
                ('data_missao', models.DateField(verbose_name='Data da Missão')),
                ('destino', models.CharField(max_length=30, verbose_name='Destino')),
                ('conteudo', tinymce.models.HTMLField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name_plural': 'Ofícios',
                'db_table': 'p1_oficios',
            },
        ),
        migrations.CreateModel(
            name='PolicialMilitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nome_guerra', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('tipo_sanguineo', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+')], max_length=2, verbose_name='Tipo Sanguíneo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
            ],
            options={
                'verbose_name': 'Policial Militar',
                'verbose_name_plural': 'Policiais',
                'db_table': 'p1_policiais',
            },
        ),
        migrations.CreateModel(
            name='TipoOficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('assunto', models.CharField(max_length=30, verbose_name='Assunto')),
                ('referencia', models.CharField(max_length=30, verbose_name='Referência')),
                ('anexo', models.CharField(max_length=30, verbose_name='Anexo')),
                ('destino', models.CharField(max_length=30, verbose_name='Destino')),
                ('conteudo', tinymce.models.HTMLField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Tipo de Ofício',
                'verbose_name_plural': 'Tipos de Ofício',
                'db_table': 'p1_tipos_oficio',
            },
        ),
        migrations.AddField(
            model_name='oficio',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='p1.TipoOficio'),
        ),
    ]
