# Generated by Django 2.1.3 on 2018-11-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='arquivo',
            field=models.FileField(default='sadasd.pdf', upload_to='oficios_arquivos'),
        ),
    ]
