# Generated by Django 2.1.3 on 2018-11-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacao',
            old_name='publicacoes',
            new_name='policial',
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
    ]
