# Generated by Django 2.1.3 on 2018-11-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0003_auto_20181109_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='p1.TipoOficio', verbose_name='Tipo'),
        ),
    ]
