# Generated by Django 2.1.3 on 2018-11-11 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0004_auto_20181109_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='policialmilitar',
            name='matricula',
            field=models.CharField(default='00000000', max_length=8, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='p1.TipoOficio', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='policialmilitar',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='policialmilitar',
            name='nome_guerra',
            field=models.CharField(max_length=30, verbose_name='Nome de Guerra'),
        ),
        migrations.AddField(
            model_name='policialmilitar',
            name='opm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='p1.Opm', verbose_name='OPM'),
        ),
    ]
