# Generated by Django 2.1.3 on 2018-11-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_auto_20181110_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Cargo')),
                ('abreviacao', models.CharField(max_length=10, verbose_name='Abreviação')),
            ],
        ),
        migrations.AlterField(
            model_name='opm',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='OPM'),
        ),
        migrations.AddField(
            model_name='policialmilitar',
            name='cargo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='p1.Cargo', verbose_name='Cargo'),
        ),
    ]
