# Generated by Django 2.1.3 on 2018-11-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0006_auto_20181110_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='policialmilitar',
            name='numero',
            field=models.CharField(default=0, max_length=6, verbose_name='Número'),
        ),
    ]
