# Generated by Django 2.1.3 on 2018-11-11 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0007_policialmilitar_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoFuncional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='policialmilitar',
            name='situacao_funcional',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='p1.SituacaoFuncional', verbose_name='Situação Funcional'),
            preserve_default=False,
        ),
    ]
