# Generated by Django 2.1.3 on 2018-11-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0008_auto_20181110_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='policialmilitar',
            name='matricula',
            field=models.CharField(default='00000000', max_length=8, unique=True, verbose_name='Matrícula'),
        ),
    ]
