# Generated by Django 2.1.3 on 2018-11-11 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0009_auto_20181110_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policialmilitar',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='p1.Cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='policialmilitar',
            name='opm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='p1.Opm', verbose_name='OPM'),
        ),
    ]
